export const services = [
  {
    id: "plumbing",
    title: "Emergency Plumbing",
    category: "Plumbing",
    tech: "Michael Rodriguez",
    rating: 4.9,
    reviews: 128,
    price: 85,
    location: "Austin, TX",
    image:
      "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "electrical",
    title: "Electrical Repair",
    category: "Electrical",
    tech: "David Chen",
    rating: 4.8,
    reviews: 96,
    price: 75,
    location: "Austin, TX",
    image:
      "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "cleaning",
    title: "Deep Home Cleaning",
    category: "Cleaning",
    tech: "Sarah Johnson",
    rating: 5.0,
    reviews: 84,
    price: 60,
    location: "Round Rock, TX",
    image:
      "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "painting",
    title: "Interior Room Painting",
    category: "Painting",
    tech: "James Wilson",
    rating: 4.9,
    reviews: 72,
    price: 120,
    location: "Pflugerville, TX",
    image:
      "https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "appliance",
    title: "Appliance Repair",
    category: "Appliance Repair",
    tech: "Priya Patel",
    rating: 4.8,
    reviews: 61,
    price: 90,
    location: "Austin, TX",
    image:
      "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "carpentry",
    title: "Custom Carpentry",
    category: "Carpentry",
    tech: "Robert Taylor",
    rating: 4.9,
    reviews: 53,
    price: 100,
    location: "Cedar Park, TX",
    image:
      "https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=900&q=80",
  },
];
export const technicians = [
  {
    slug: "michael-rodriguez",
    name: "Michael Rodriguez",
    profession: "Licensed Plumber",
    location: "Austin, TX",
    rating: 4.9,
    reviews: 128,
    years: 12,
    jobs: 348,
    price: 85,
    avatar: "https://i.pravatar.cc/160?img=12",
    color: "bg-blue-100",
  },
  {
    slug: "sarah-johnson",
    name: "Sarah Johnson",
    profession: "Professional Cleaner",
    location: "Round Rock, TX",
    rating: 5.0,
    reviews: 84,
    years: 8,
    jobs: 214,
    price: 60,
    avatar: "https://i.pravatar.cc/160?img=47",
    color: "bg-amber-100",
  },
  {
    slug: "david-chen",
    name: "David Chen",
    profession: "Master Electrician",
    location: "Austin, TX",
    rating: 4.8,
    reviews: 96,
    years: 15,
    jobs: 402,
    price: 75,
    avatar: "https://i.pravatar.cc/160?img=68",
    color: "bg-emerald-100",
  },
  {
    slug: "james-wilson",
    name: "James Wilson",
    profession: "Painting Specialist",
    location: "Pflugerville, TX",
    rating: 4.9,
    reviews: 72,
    years: 10,
    jobs: 187,
    price: 120,
    avatar: "https://i.pravatar.cc/160?img=11",
    color: "bg-violet-100",
  },
];
export const categories = [
  { name: "Plumbing", icon: "◉", tint: "bg-blue-50 text-blue-600" },
  { name: "Electrical", icon: "ϟ", tint: "bg-amber-50 text-amber-600" },
  { name: "Cleaning", icon: "✦", tint: "bg-emerald-50 text-emerald-600" },
  { name: "Painting", icon: "◒", tint: "bg-violet-50 text-violet-600" },
  { name: "Appliance Repair", icon: "▦", tint: "bg-rose-50 text-rose-600" },
  { name: "Carpentry", icon: "⌂", tint: "bg-orange-50 text-orange-600" },
];
export type Service = (typeof services)[number];
export type Technician = (typeof technicians)[number];
